# Vector Log Aggregation Configuration

api:
  enabled: true
  address: 0.0.0.0:9001

sources:
  docker_host:
    type: docker_logs
    exclude_containers:
      - vector

transforms:
  project_logs:
    type: remap
    inputs:
      - docker_host
    source: |-
      .project = "default"
      .event_message = del(.message)
      .appname = del(.container_name)
      del(.container_created_at)
      del(.container_id)
      del(.source_type)
      del(.stream)
      del(.label)
      del(.image)
      del(.host)
      del(.timestamp)

sinks:
  logflare:
    type: http
    method: post
    batch:
      max_bytes: 2049000
      timeout_secs: 2
    compression: gzip
    encoding:
      codec: json
    healthcheck:
      enabled: true
    inputs:
      - project_logs
    uri: http://analytics:4000/api/logs?source_name=docker_logs&api_key=${LOGFLARE_API_KEY}
    request:
      headers:
        Content-Type: application/json


