name: Workflow
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  typescript:
    name: ʦ TypeScript
    timeout-minutes: 10
    runs-on: ubuntu-latest
    env:
      SERVICE_ROLE_KEY: ${{ secrets.SERVICE_ROLE_KEY }}
      SUPABASE_DATABASE_URL: ${{ secrets.SUPABASE_DATABASE_URL }}
      DO_NOT_TRACK: 1
      TURBO_SCM_BASE: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.sha || github.event.before }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Typecheck
        run: pnpm run typecheck

      - name: Lint
        run: pnpm run lint

  unit:
    name: ⚫️ Unit Test
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run Unit Tests
        run: pnpm run test:unit

  test:
    name: ⚫️ Test
    timeout-minutes: 30
    runs-on: ubuntu-latest
    if: ${{ vars.ENABLE_E2E_JOB == 'true' }}
    env:
      SERVICE_ROLE_KEY: ${{ secrets.SERVICE_ROLE_KEY }}
      SUPABASE_DATABASE_URL: ${{ secrets.SUPABASE_DATABASE_URL }}
      DO_NOT_TRACK: 1
      CI: true
      TURBO_SCM_BASE: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.sha || github.event.before }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Store Playwright's Version
        run: |
          PLAYWRIGHT_VERSION=$(pnpm ls @playwright/test --filter e2e | grep @playwright | sed 's/.*@//')
          echo "Playwright's Version: $PLAYWRIGHT_VERSION"
          echo "PLAYWRIGHT_VERSION=$PLAYWRIGHT_VERSION" >> $GITHUB_ENV

      - name: Cache Playwright Browsers for Playwright's Version
        id: cache-playwright-browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-browsers-${{ env.PLAYWRIGHT_VERSION }}

      - name: Install Playwright Browsers
        if: steps.cache-playwright-browsers.outputs.cache-hit != 'true'
        run: pnpm exec ./apps/e2e/node_modules/.bin/playwright install --with-deps

      - name: Supabase CLI
        uses: supabase/setup-cli@v1

      - name: Supabase Server
        run: pnpm run supabase:web:start -- -x studio,migra,deno-relay,pgadmin-schema-diff,imgproxy,logflare

      - name: Add API env variables
        run: mv apps/api/.env.template apps/api/.env

      - name: Add APP env variables
        run: mv apps/app/.env.template apps/app/.env

      - name: Add E2E env variables
        run: mv apps/e2e/.env.template apps/e2e/.env

      - name: Run Supabase tests
        run: pnpm --filter app supabase:test &

      - name: Run API
        run: pnpm --filter api dev &

      - name: Run APP
        run: pnpm --filter app dev &

      - name: Run Playwright tests
        run: |
          pnpm run test:e2e

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: apps/e2e/playwright-report/
          retention-days: 7
